import { Branch, Cable, CalculationParameters } from './types';

export const DEFAULT_PARAMETERS: CalculationParameters = {
  spare_margin_pct: 20.0,
  control_fill_pct: 40.0,
  default_tray_height_mm: 60.0,
  add_metallic_divider: false,
  divider_width_mm: 15.0,
  default_power_od_mm: 25.0,
  default_control_od_mm: 14.0,
  default_signal_od_mm: 10.0,
  default_data_od_mm: 8.5,
  default_global_od_mm: 15.0,
  custom_od_by_type: {
    '400V Feeder': 28.0,
    'PROFINET': 7.5,
    'Cat6 Ethernet': 6.5,
  },
  single_core_power_formation: 'trefoil',
  control_cable_laying_method: 'multi_layer',
};

export const SAMPLE_BRANCHES: Branch[] = [
  // --- LEVEL 1 (Substation & Main Power Distribution) ---
  {
    branch_id: "BR_L1_01",
    node_from: "TRANSF_01",
    node_to: "MCC_L1",
    level: "Level 1",
    branch_type: "horizontal",
    length_m: 12.0,
    tray_height_mm: 100.0,
  },
  {
    branch_id: "BR_L1_02",
    node_from: "MCC_L1",
    node_to: "DCS_RACK_L1",
    level: "Level 1",
    branch_type: "horizontal",
    length_m: 8.5,
    tray_height_mm: 60.0,
  },
  {
    branch_id: "BR_L1_03",
    node_from: "MCC_L1",
    node_to: "JUNC_L1_EAST",
    level: "Level 1",
    branch_type: "horizontal",
    length_m: 14.5,
    tray_height_mm: 60.0,
  },
  {
    branch_id: "BR_L1_04",
    node_from: "DCS_RACK_L1",
    node_to: "JUNC_L1_EAST",
    level: "Level 1",
    branch_type: "horizontal",
    length_m: 10.0,
    tray_height_mm: 60.0,
  },
  {
    branch_id: "BR_L1_05",
    node_from: "JUNC_L1_EAST",
    node_to: "COOLING_PUMP_P1",
    level: "Level 1",
    branch_type: "horizontal",
    length_m: 7.5,
    tray_height_mm: 60.0,
  },
  {
    branch_id: "BR_L1_06",
    node_from: "JUNC_L1_EAST",
    node_to: "TEMP_TRANSMITTER_TT101",
    level: "Level 1",
    branch_type: "horizontal",
    length_m: 6.0,
    tray_height_mm: 60.0,
  },
  {
    branch_id: "BR_L1_07",
    node_from: "MCC_L1",
    node_to: "RISER_EAST_L1",
    level: "Level 1",
    branch_type: "horizontal",
    length_m: 18.0,
    tray_height_mm: 100.0,
  },
  {
    branch_id: "BR_L1_08",
    node_from: "MCC_L1",
    node_to: "COMPRESSOR_CP1",
    level: "Level 1",
    branch_type: "horizontal",
    length_m: 11.0,
    tray_height_mm: 60.0,
  },

  // --- VERTICAL RISER 1 (Level 1 to Level 2) ---
  {
    branch_id: "RISER_E_L1_L2",
    node_from: "RISER_EAST_L1",
    node_to: "RISER_EAST_L2",
    level: "Transition",
    branch_type: "vertical",
    length_m: 5.0,
    tray_height_mm: 100.0,
  },

  // --- LEVEL 2 (Process Tanks & Mixing Operations) ---
  {
    branch_id: "BR_L2_01",
    node_from: "RISER_EAST_L2",
    node_to: "FEEDER_PANEL_L2",
    level: "Level 2",
    branch_type: "horizontal",
    length_m: 15.0,
    tray_height_mm: 100.0,
  },
  {
    branch_id: "BR_L2_02",
    node_from: "FEEDER_PANEL_L2",
    node_to: "MCC_L2",
    level: "Level 2",
    branch_type: "horizontal",
    length_m: 6.0,
    tray_height_mm: 100.0,
  },
  {
    branch_id: "BR_L2_03",
    node_from: "FEEDER_PANEL_L2",
    node_to: "PLC_PANEL_L2",
    level: "Level 2",
    branch_type: "horizontal",
    length_m: 9.0,
    tray_height_mm: 60.0,
  },
  {
    branch_id: "BR_L2_04",
    node_from: "MCC_L2",
    node_to: "MIXER_MOTOR_M2",
    level: "Level 2",
    branch_type: "horizontal",
    length_m: 12.5,
    tray_height_mm: 60.0,
  },
  {
    branch_id: "BR_L2_05",
    node_from: "PLC_PANEL_L2",
    node_to: "VALVE_CLUSTER_V1",
    level: "Level 2",
    branch_type: "horizontal",
    length_m: 8.0,
    tray_height_mm: 60.0,
  },
  {
    branch_id: "BR_L2_06",
    node_from: "PLC_PANEL_L2",
    node_to: "JUNC_L2_WEST",
    level: "Level 2",
    branch_type: "horizontal",
    length_m: 11.5,
    tray_height_mm: 60.0,
  },
  {
    branch_id: "BR_L2_07",
    node_from: "JUNC_L2_WEST",
    node_to: "PRESSURE_SENSOR_PT202",
    level: "Level 2",
    branch_type: "horizontal",
    length_m: 5.0,
    tray_height_mm: 60.0,
  },
  {
    branch_id: "BR_L2_08",
    node_from: "RISER_EAST_L2",
    node_to: "RISER_EAST_L2_L3",
    level: "Level 2",
    branch_type: "horizontal",
    length_m: 4.0,
    tray_height_mm: 100.0,
  },

  // --- VERTICAL RISER 2 (Level 2 to Level 3) ---
  {
    branch_id: "RISER_E_L2_L3",
    node_from: "RISER_EAST_L2_L3",
    node_to: "RISER_EAST_L3",
    level: "Transition",
    branch_type: "vertical",
    length_m: 5.5,
    tray_height_mm: 100.0,
  },

  // --- LEVEL 3 (Furnace Mezzanine & Rooftop Exhaust) ---
  {
    branch_id: "BR_L3_01",
    node_from: "RISER_EAST_L3",
    node_to: "REMOTE_IO_L3",
    level: "Level 3",
    branch_type: "horizontal",
    length_m: 14.0,
    tray_height_mm: 60.0,
  },
  {
    branch_id: "BR_L3_02",
    node_from: "RISER_EAST_L3",
    node_to: "FOREHEARTH_FAN_M1",
    level: "Level 3",
    branch_type: "horizontal",
    length_m: 22.0,
    tray_height_mm: 100.0,
  },
  {
    branch_id: "BR_L3_03",
    node_from: "RISER_EAST_L3",
    node_to: "EXHAUST_BLOWER_B1",
    level: "Level 3",
    branch_type: "horizontal",
    length_m: 18.5,
    tray_height_mm: 100.0,
  },
];

export const SAMPLE_CABLES: Cable[] = [
  // Heavy Power Feeders
  { cable_tag: "C_PWR_MAIN_01", source_node: "TRANSF_01", dest_node: "MCC_L1", cable_type: "power", od_mm: 42.5, count: 3 },
  { cable_tag: "C_PWR_FEED_L2", source_node: "MCC_L1", dest_node: "FEEDER_PANEL_L2", cable_type: "power", od_mm: 36.0, count: 1 },
  { cable_tag: "C_PWR_MCC2_IN", source_node: "FEEDER_PANEL_L2", dest_node: "MCC_L2", cable_type: "power", od_mm: 32.0, count: 1 },
  { cable_tag: "C_PWR_COMPRESSOR", source_node: "MCC_L1", dest_node: "COMPRESSOR_CP1", cable_type: "power", od_mm: 38.0, count: 1 },
  { cable_tag: "C_PWR_PUMP1", source_node: "MCC_L1", dest_node: "COOLING_PUMP_P1", cable_type: "power", od_mm: 24.5, count: 1 },
  { cable_tag: "C_PWR_MIXER", source_node: "MCC_L2", dest_node: "MIXER_MOTOR_M2", cable_type: "power", od_mm: 22.8, count: 1 },
  { cable_tag: "C_PWR_ROOF_FAN", source_node: "MCC_L1", dest_node: "FOREHEARTH_FAN_M1", cable_type: "power", od_mm: 28.4, count: 1 },
  { cable_tag: "C_PWR_BLOWER", source_node: "MCC_L2", dest_node: "EXHAUST_BLOWER_B1", cable_type: "power", od_mm: 31.2, count: 1 },

  // Control & Interlock Cables
  { cable_tag: "C_CTRL_PUMP1", source_node: "DCS_RACK_L1", dest_node: "COOLING_PUMP_P1", cable_type: "control", od_mm: 14.0, count: 1 },
  { cable_tag: "C_CTRL_VALVES", source_node: "PLC_PANEL_L2", dest_node: "VALVE_CLUSTER_V1", cable_type: "control", od_mm: 16.5, count: 2 },
  { cable_tag: "C_CTRL_FAN_RUN", source_node: "DCS_RACK_L1", dest_node: "FOREHEARTH_FAN_M1", cable_type: "control", od_mm: 12.5, count: 2 },
  { cable_tag: "C_CTRL_MIXER", source_node: "PLC_PANEL_L2", dest_node: "MIXER_MOTOR_M2", cable_type: "control", od_mm: 13.0, count: 1 },
  { cable_tag: "C_CTRL_COMPR", source_node: "DCS_RACK_L1", dest_node: "COMPRESSOR_CP1", cable_type: "control", od_mm: 15.0, count: 1 },

  // Instrumentation Signals
  { cable_tag: "C_SIG_TT101", source_node: "JUNC_L1_EAST", dest_node: "TEMP_TRANSMITTER_TT101", cable_type: "signal", od_mm: 8.8, count: 4 },
  { cable_tag: "C_SIG_PT202", source_node: "JUNC_L2_WEST", dest_node: "PRESSURE_SENSOR_PT202", cable_type: "signal", od_mm: 9.2, count: 3 },

  // Industrial Ethernet & Fieldbus
  { cable_tag: "C_DATA_DCS_PLC", source_node: "DCS_RACK_L1", dest_node: "PLC_PANEL_L2", cable_type: "data", od_mm: 11.2, count: 2 },
  { cable_tag: "C_DATA_PLC_RIO3", source_node: "PLC_PANEL_L2", dest_node: "REMOTE_IO_L3", cable_type: "data", od_mm: 10.5, count: 1 },
  { cable_tag: "C_BUS_MODBUS_L1", source_node: "DCS_RACK_L1", dest_node: "MCC_L1", cable_type: "bus", od_mm: 9.5, count: 1 },
  { cable_tag: "C_BUS_PROFINET_L2", source_node: "PLC_PANEL_L2", dest_node: "MCC_L2", cable_type: "bus", od_mm: 9.8, count: 1 },
];
